version: "3.8"
services:
  kafka1:
    container_name: kafka1
    image: erkansirin78/kafka:3.2.0
    build: 
      context: .
    ports:
        - "9192:9192"
    volumes:
    - ./config/kafka1/server.properties:/kafka/config/server.properties
    - ./data/kafka1/:/data/kafka/
  kafka2:
    container_name: kafka2
    image: erkansirin78/kafka:3.2.0
    build: 
      context: .
    ports:
        - "9292:9192"
    volumes:
    - ./config/kafka2/server.properties:/kafka/config/server.properties
    - ./data/kafka2/:/data/kafka/
  kafka3:
    container_name: kafka3
    image: erkansirin78/kafka:3.2.0
    build: 
      context: .
    ports:
        - "9392:9192"
    volumes:
    - ./config/kafka3/server.properties:/kafka/config/server.properties
    - ./data/kafka3/:/data/kafka/
